modified config.yml file using when condition

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,13 +25,27 @@ jobs:
       - run:
           name: Run tests on headless Firefox
           #https://support.circleci.com/hc/en-us/articles/360057590591-Ignoring-A-Failure-In-A-Step
-          command: npm run testcase1 
-      
+          command: npm run testcase1 || true
+      - run:
+          name: Run commnads
+          command: |
+              echo "I will exit success status"
+              exit 0
       - run:
           name: Run on fail status
           command: |
               echo "I am result of above failed job"
           when: on_fail
+      - run:
+          name: Run on fail status
+          command: |
+              echo "I am result of above success/failed job"
+          when: always
+      - run:
+          name: Run on fail status
+          command: |
+              echo "I am result of above success job"
+          when: on_success
 
   edge:
     docker:
